import { FileText } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-surface-50">
      <div className="bg-hero-gradient text-white py-16 px-4">
        <div className="max-w-3xl mx-auto text-center">
          <div className="w-14 h-14 bg-white/20 rounded-2xl flex items-center justify-center mx-auto mb-4">
            <FileText className="w-7 h-7 text-white" />
          </div>
          <h1 className="text-3xl font-bold mb-3">Terms of Service</h1>
          <p className="text-white/70 text-sm">Last updated: June 2026</p>
        </div>
      </div>

      <div className="max-w-3xl mx-auto px-4 py-12">
        <div className="card p-8 space-y-6 text-sm text-surface-700 leading-relaxed">

          <section>
            <h2 className="text-lg font-bold text-surface-900 mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using NyumbaLink, you agree to be bound by these Terms of Service
              and our Privacy Policy. If you do not agree, please do not use our services.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-surface-900 mb-3">2. Description of Service</h2>
            <p>
              NyumbaLink is an AI-powered accommodation search platform connecting renters with
              verified landlords in Dar es Salaam, Tanzania. We provide listing discovery,
              fair-price analysis, and payment facilitation. We are not a party to any rental
              agreement between landlords and renters.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-surface-900 mb-3">3. User Responsibilities</h2>
            <p>As a user of NyumbaLink, you agree to:</p>
            <ul className="list-disc pl-5 space-y-1 mt-2">
              <li>Provide accurate and truthful information when registering or listing a property</li>
              <li>Not use the platform to post fraudulent, misleading, or illegal listings</li>
              <li>Respect the privacy and rights of other users</li>
              <li>Not attempt to circumvent our pricing or verification systems</li>
              <li>Comply with all applicable Tanzanian laws and regulations</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-surface-900 mb-3">4. Landlord Obligations</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>Listings must accurately describe the property and its condition</li>
              <li>Listed prices must reflect actual rental amounts — price manipulation is prohibited</li>
              <li>Landlords must complete identity verification (NIDA) to publish listings</li>
              <li>Landlords flagged for predatory broker (dalali) behaviour may be suspended</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-surface-900 mb-3">5. Payments</h2>
            <p>
              Payments processed through NyumbaLink use M-Pesa via Vodacom Tanzania.
              NyumbaLink charges a service fee for premium listing features.
              Refunds are subject to our refund policy available at{" "}
              <a href="/faq" className="text-primary-600 hover:underline">our FAQ page</a>.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-surface-900 mb-3">6. AI and Price Estimates</h2>
            <p>
              Fair price estimates generated by our ML model are indicative only and do not
              constitute financial or legal advice. Actual market prices may vary. NyumbaLink
              is not liable for decisions made based on price estimates.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-surface-900 mb-3">7. Limitation of Liability</h2>
            <p>
              NyumbaLink is a marketplace platform. We are not responsible for the condition
              of properties, the conduct of landlords or renters, or any disputes arising
              from rental agreements. Our liability is limited to the amount paid to us
              for platform services in the preceding 3 months.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-surface-900 mb-3">8. Termination</h2>
            <p>
              We reserve the right to suspend or terminate accounts that violate these terms,
              engage in fraud, or harm other users. You may delete your account at any time
              from your profile settings.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-surface-900 mb-3">9. Governing Law</h2>
            <p>
              These terms are governed by the laws of the United Republic of Tanzania.
              Disputes shall be resolved in the courts of Dar es Salaam.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-surface-900 mb-3">10. Contact</h2>
            <p>
              NyumbaLink, Dar es Salaam, Tanzania<br />
              Email: <a href="mailto:legal@nyumbalink.co.tz" className="text-primary-600 hover:underline">legal@nyumbalink.co.tz</a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
